learning_passport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('',include('events.urls')),
    path('',include('articles.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

from django.contrib.auth import views as auth_views
 

from users.views import ResetPasswordView
 
urlpatterns = [
    path('', views.dashboardView, name="dashboard"),
    path('login', views.loginView, name="login"),
    path('logout', views.logoutView, name="logout"),
    path('register', views.registerView, name="register"),
    path('edit-profile/<str:id>', views.editProfile, name="edit-profile"),
    path('manage-student', views.manageStudent, name="manage-student"),
    path('manage-lecturer', views.manageLecturer, name="manage-lecturer"),
    path('change-password', views.resetPasswordView, name="change-password"),
    path('password-reset', ResetPasswordView.as_view(), name="password_reset"),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
     path('generate_transcript/<int:user_id>/', views.generateTranscriptView, name="generate-transcript"),
     path('get-student-details/<int:student_id>/', views.get_student_details, name='get-student-details'),
     path('get-lecturer-details/<int:lecturer_id>/', views.get_lecturer_details, name='get-lecturer-details'),
     path('get-semester-details/<int:semester_id>/', views.get_semester_details, name='get-semester-details'),
     path('semester-dates', views.semesterDatesView, name="semesters"),
     path('graduate-report', views.graduateReportView, name="graduate-report"),
     path('inquiry', views.inquiryView, name="inquiry"),
     path('active-report', views.activeReportView, name="active-report"),
     path('postgrad', views.postgradDetailsView, name="postgrad"),
     path('generate-pdf/<int:student_id>', views.generatePDF, name="generate-pdf"),
     path('download-all-transcripts/<int:semester_id>', views.download_all_transcripts, name='download-all-transcripts'),
     path('print-all-transcripts', views.printAllView, name="print-all-transcripts")
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
# Create your models here.

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users require an email field')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)
    
class User(AbstractUser):
    objects = UserManager()
    email = models.EmailField('email adress', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    first_name = None
    last_name = None
    username = None
    full_name = models.CharField(max_length=50, null=True)
    name_chi = models.CharField(max_length=50, null=True)
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(auto_now=True)
    ROLES = (
        ("SUPER ADMIN", "SUPER ADMIN"),
        ("ADMIN", "ADMIN"),
        ("HEAD OF DEPARTMENT", "HEAD OF DEPARTMENT"),
        ("LECTURER", "LECTURER"),
        ("STUDENT", "STUDENT"),
    )  
    role = models.CharField(max_length=20, choices=ROLES, default="STUDENT")
    is_active = models.BooleanField(default=True)
    contact = models.CharField(max_length=20, null=True)
    address = models.CharField(max_length=100, null=True)
    date_inactive = models.DateField(null=True)

class Semester (models.Model):
    academic_year = models.CharField(max_length=7)
    semester = models.SmallIntegerField()
    start = models.DateField(null=True)
    end = models.DateField(null=True)
    
class Lecturer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Position = (
        (1, "Adjunct Professor"),
        (2, "Associate Professor"),
        (3, "Senior Lecturer"),
        (4, "Lecturer"),
        (5, "Post Doctoral Research Fellow"),       
    )
    position = models.SmallIntegerField(choices=Position)

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    matric_no = models.CharField(max_length=10)
    Program = (
        (1, "Bachelor of Arts Chinese Studies"),
        (2, "Master of Chinese Studies (Coursework)"),
        (3, "Master of Arts (Research)"),
        (4, "Doctor of Philosophy (Ph.D)"),
    )
    program = models.SmallIntegerField(choices=Program)
    lecturer = models.ForeignKey(Lecturer, on_delete=models.PROTECT)
    enrol_sem = models.ForeignKey(Semester, on_delete=models.SET_NULL, null=True, related_name="enrol_sem")
    grad_sem = models.ForeignKey(Semester, on_delete=models.SET_NULL, null=True, related_name="grad_sem")
    rm_date = models.DateTimeField(null=True)
    pd_date = models.DateTimeField(null=True)
    cd_date = models.DateTimeField(null=True)
    viva_date = models.DateTimeField(null=True)
    rm_status = models.BooleanField(default=False)
    pd_status = models.BooleanField(default=False)
    cd_status = models.BooleanField(default=False)
    viva_status = models.BooleanField(default=False)

class Organisation(models.Model):
    name = models.CharField(max_length=100)
    year = models.IntegerField()
    internal = models.BooleanField()
    file = models.FileField(upload_to='org_com/')
    filename = models.CharField(max_length=100, null = True)
    file_by = models.ForeignKey(Student, on_delete=models.SET_NULL, null=True)
    status = models.BooleanField(null=True)

class OrgComittee(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    org = models.ForeignKey(Organisation,on_delete=models.CASCADE)
    position = models.CharField(max_length=100)
    file = models.FileField(upload_to='org_external/', null=True)
    filename = models.CharField(max_length=100, null=True)
    status = models.BooleanField(null=True)

templates/admin_attendance.html
{% extends "sidebar.html" %}
{% block title %} Attendance {% endblock title%}
{% block content %}
{% load static %}

<head>    
<script>
    function checkAll(o) {
        var boxes = document.getElementsByTagName("input");
        for (var x = 0; x < boxes.length; x++) {
          var obj = boxes[x];
          if (obj.type == "checkbox") {
            if (obj.name != "check")
              obj.checked = o.checked;
          }
        }
      }
</script>
</head>

<br>
<h5>{{event.e_name}} {% if event.start %} ({{event.start.year}}) {% endif %} </h5>
<br>
<form method="POST">
  {% csrf_token %}
  {% if not event.enable_attendance %}
  <button type="submit" name="enable" class="btn btn-success" value="{{event.id}}" onclick="return confirm('Confirm to enable attendance for {{event.e_name}}?')">Enable Attendance</button>
  {% else %}
  <button type="disable" name="disable" class="btn btn-danger" value="{{event.id}}" onclick="return confirm('Confirm to disable attendance for {{event.e_name}}?')">Disable Attendance</button>
  {% endif %}
</form>
<br>

<input id="search" type="text" class="form-control" placeholder="Search for matric number..." onkeyup="searchFunction()">
    


<br><br>
{% if participants or students %}
<form method="POST">
    {% csrf_token %}
 
    <table id="attendance_table" class= "table table-striped table-responsive">
       
        <thead>
            <tr>
                <div class="checkbox select-all">
                    <input id="check-all" class="form-check-input" type="checkbox" id="cc" onclick="javascript:checkAll(this)"/>
                    <label for="check-all">Check All</label>
                  </div>
                <th>Name</th>
                <th>Matric No. </th>
                <th>Attendance</th>
            </tr>
        </thead>
        <tbody>
            
            {% for participant in participants %}
                <tr>
                    <td>{{ participant.student.user.full_name }}</td>
                    <td>{{ participant.student.matric_no }}</td>
                    <div class="checkbox rows">
                    <td><input class="form-check-input" type="checkbox" name="{{ participant.student.id }}" {% if participant.attendance %}checked{% endif %}></td>
                    </div>
                </tr>
            {% endfor %}
            {% for student in students %}
                <tr>
                    <td>{{ student.user.full_name }}</td>
                    <td>{{ student.matric_no }}</td>
                    <div class="checkbox rows">
                    <td><input class="form-check-input" type="checkbox" name="{{ student.id }}" {% if participant.attendance %}checked{% endif %}></td>
                    </div>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <button type="submit" class="btn btn-primary">Save Attendance</button>
    <script>
        $('#all').change(function(e) {
            if (e.currentTarget.checked) {
            $('.rows').find('input[type="checkbox"]').prop('checked', true);
          } else {
              $('.rows').find('input[type="checkbox"]').prop('checked', false);
            }
          });
    </script>
</form> 
{% else %}
<center><sub>No student.</sub></center>
{% endif %}
<script>
    function searchFunction() {
      // Declare variables
      var input, filter, table, tr, matric,name, i, txtValue;
      input = document.getElementById("search");
      filter = input.value.toUpperCase();
      table = document.getElementById("attendance_table");
      tr = table.getElementsByTagName("tr");
      // Loop through all table rows, and hide those who don't match the search query
      for (i = 0; i < tr.length; i++) {
        matric = tr[i].getElementsByTagName("td")[1];
        name = tr[i].getElementsByTagName("td")[0];
        if (matric || name) {
          matricValue = matric.textContent || matric.innerText;
          nameValue = name.textContent || name.innerText;
          if (matricValue.toUpperCase().indexOf(filter) > -1  || nameValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
      }
    }
    </script>

{% endblock %}

templates/dashboard_lecturer.html
{% extends "sidebar.html" %}
{% block content %}
{% load static %}

<head>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">

    <script>
      $(document).ready(function() {
          // Function to toggle the class based on window width
          function toggleClassBasedOnWidth() {
              var windowWidth = $(window).width();
              var $container = $("#flex-container");
              var $right = $("#right");
              var $card1 = $("#card1");
              var $card2 = $("#card2");
              var $card3 = $("#card3");
              var $card4 = $("#card4");
              if (windowWidth > 1200) {
                  $container.css('display', 'flex');
                  $right.css('display', 'flex');
                  $card1.css('width', '');
                  $card2.css('width', '');
                  $card3.css('width', '');
                  $card4.css('width', '');
              } else {
                  $container.css('display', 'block');
                  $right.css('display', 'block');
                  $card1.css('width', '100%');
                  $card2.css('width', '100%');
                  $card3.css('width', '100%');
                  $card4.css('width', '100%');
              }
          }
          
          // Call the function on page load
          toggleClassBasedOnWidth();
          
          // Bind the function to the window resize event
          $(window).resize(function() {
              toggleClassBasedOnWidth();
          });
      });
    
  </script>
  
</head>

<h1> Dashboard </h1>
<br>

<div id="flex-container" class="container">
  <div class="left-side" style="display:flex;">
    <div class="card profile-card">
        <div class="card-header">
            <h4 class="card-title">My Profile</h4>
        </div>
        <div class="card-body">
            <sub>Name</sub>
            <p><strong>{{lecturer.user.full_name}}</strong></p>
            <sub>Position</sub>
            <p><strong>{{lecturer.get_position_display}}</strong></p>
            <sub>Email</sub>
            <p><strong>{{lecturer.user.email}}</strong></p>
            <sub>Contact</sub>
            <p><strong>{{lecturer.user.contact}}</strong></p>
            <sub>Address</sub>
            <p><strong>{{lecturer.user.address}}</strong></p>
        </div>
        <div class="card-footer">
            <center>
                <a href="{% url 'edit-profile' lecturer.user.id %}">Edit Profile Details</a>
            </center>
        </div>
    </div>

    <div class="gap"></div>

    <div id="right" class="info-cards">
      <div id="card1" class="card info-card card1">
        <div class="card-body">
          <center>
            <div class="card-text">
              <h1><i class="fa-solid fa-graduation-cap" style="color: #6151fb"></i></h1>
              <strong>
                <p class="info-title">Bachelor of Arts<br>Chinese Studies</p>
              </strong>
              <h3>{{undergrad}}</h3>
            </div>
          </center>
        </div>
      </div>
      <div id="card2" class="card info-card card2">
        <div class="card-body">
          <center>
            <div class="card-text">
              <h1><i class="fa-solid fa-book" style="color: #ed1d4d"></i></h1>
              <strong>
                <p class="info-title">Master of Chinese Studies<br>(Coursework)</p>
              </strong>
              <h3>{{master_cw}}</h3>
            </div>
          </center>
        </div>
      </div>
      <div id="card3" class="card info-card card3">
        <div class="card-body">
          <center>
            <div class="card-text">
              <h1><i class="fa-solid fa-flask" style="color: #1b8be3"></i></h1>
              <strong>
                <p class="info-title">Master of Arts <br>(Research) </p>
              </strong>
              <h3>{{master_re}}</h3>
            </div>
          </center>
        </div>
      </div>
      <div id="card4" class="card info-card card4">
        <div class="card-body">
          <center>
            <div class="card-text">
              <h1><i class="fa-solid fa-clipboard-check" style="color: #ffa01f"></i></h1>
              <strong>
                <p class="info-title">Doctor of Philosophy<br>(Ph.D) </p>
              </strong>
              <h3>{{phd}}</h3>
            </div>
          </center>
        </div>
      </div>
    </div>
  </div>
  {% if events or announcements %}
  <div class="right-side">
    {% if events %}
    <div>
      <h5 class="fw-bold mb-1">Registered Events</h5>
      <a class="mb-0" href="{% url 'attendance' %}">View all</a>
    </div>

    {% for event in events %}
    <a href="{% url 'event-detail' event.id %}">
      <div class="card border border-info">
        <div class="card-body">
          <p><strong>{{event.e_name}}</strong>
            <br>{{event.start.date}}
          </p>
        </div>
      </div>
    </a>
    <br>
    {% endfor %}

    {% endif %}

    {% if announcements %}
    <div>
      <h5 class="fw-bold mb-1">Announcements</h5>
      <a class="mb-0" href="{% url 'announcements' %}">View all</a>
    </div>
    {% for ann in announcements %}
    <div class="card border border-info">
      <div class="card-header">
        <strong>{{ann.title}}</strong>
      </div>
      <div class="card-body">
        {{ann.content}}
      </div>
    </div>
    <br>
    {% endfor %}
    {% endif %}
  </div>
  {% endif %}
</div>

<br>


{% endblock %}

templates/manage_lecturer.html
{% extends "sidebar.html" %}
{% block content %}
{% load static %}
<script>
    $(document).ready(function () {
        $('.manage-lecturer').click(function () {
            console.log()
            var lecturerId = $(this).data('lecturer-id');

            // Make an AJAX request to retrieve the event details
            $.ajax({
                url: '/get-lecturer-details/' + lecturerId + '/',  // URL to your Django view for fetching event details
                type: 'GET',

                success: function (response) {
                    lecturer_id = response.id;
                    $('#manage-lecturer').val(lecturer_id);
                    lecturer_name = response.name;
                    console.log(lecturer_name)
                    $('#lecturer_name').val(lecturer_name);
                    lecturer_position = response.position;
                    $('#lecturer_position').val(lecturer_position);
                    var lecturer_active = response.active
                    console.log(lecturer_active)
                    if (lecturer_active == true) {
                        $('#lecturer_active').prop('checked', true);
                    }
                    else {
                        $('#lecturer_active').prop('checked', false);
                    }

                },
                error: function (xhr, status, error) {
                    console.log(error);  // Handle the error if necessary
                }
            });
        });
    });

    function search() {
      // Declare variables
      var input, filter, table, tr, matric,name, i, txtValue;
      input = document.getElementById("search_text");
      filter = input.value.toUpperCase()
      table = document.getElementById("lecturer_table");
      tr = table.getElementsByTagName("tr");
    
      // Loop through all table rows, and hide those who don't match the search query
      for (i = 0; i < tr.length; i++) {
        // matric = tr[i].getElementsByTagName("td")[1];
        name = tr[i].getElementsByTagName("td")[0];
        // console.log(name)
        
        if (name) {
        //   matricValue = matric.textContent || matric.innerText;
          nameValue = name.textContent || name.innerText;
        //   console.log(matricValue)
          console.log(nameValue)
          if (nameValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
      }
    }

</script>

<div>
<h3>Head of Department: {{hod_name}}</h3>

<button class="btn btn-primary" data-mdb-toggle="modal" data-mdb-target="#hod_modal">Change Head of Department</button>
</div>
<hr>
<center>
    <input id="search_text" type="text" class="form-control" style="width:50%" placeholder="Search for lecturer's name..." onkeyup="search()">
    </center>

<br>

{% if lecturers_students %}
<form method="POST">
    {% csrf_token %}
    
    <table id="lecturer_table" class="table table-striped">
        <thead class="bg-light">
            <tr>
                <th>Name</th>
                <th>Bac. Chinese Studies</th>
                <th>Master (Courserwork)</th>
                <th>Master (Research)</th>
                <th>Ph.D</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        {% for lecturer,bac_count, cw_count, re_count, phd_count in lecturers_students %}
        <tr>
            <td>
                <div class="ms-3">
                    <p class="fw-bold mb-1">{{lecturer.user.full_name}}</p>
                    <p class="text-muted mb-0">{{lecturer.get_position_display}}</p>
                </div>
            </td>
            <td>
                {{bac_count}}
            </td>
            <td>
                {{cw_count}}
            </td>
            <td>
                {{re_count}}
            </td>
            <td>
                {{phd_count}}
            </td>
            {% if lecturer.user.is_active %}
            <td><span class="badge rounded-pill badge-success">Active</span></td>
            {% else %}
            <td><span class="badge rounded-pill badge-danger">Inactive</span></td>
            {% endif %}
            <td>
                <button type="button" class="manage-lecturer btn btn-floating" data-mdb-toggle="modal" data-mdb-target="#edit_modal"
                    data-lecturer-id="{{ lecturer.id }}">
                    <i class="fas fa-edit"></i>
                </button>
                &nbsp;
                <button type="submit" class="btn btn-danger btn-floating" value="{{lecturer.id}}" name="delete-lecturer" onclick="return confirm('Confirm to delete lecturer {{lecturer.user.full_name}}?')">
                    <i class="fas fa-trash"></i>
                    
                </button>
            </td>

        </tr>
        {% endfor %}
    </table>
</form>
{% else %}
<center><sub>No lecturer.</sub></center>
{% endif %}
<!-- Edit Modal -->
<form method="POST">
    {% csrf_token %}
    <div class="modal fade" id="edit_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Manage Lecturer Details</h5>
                    <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                    <div class="form-outline">
                        <input class="form-control active" id="lecturer_name" name="lecturer_name" type="text" required>
                        <label class="form-label" for="lecturer_name" style="margin-left: 0px;">Name</label>
                        <div class="form-notch">
                            <div class="form-notch-leading" style="width: 9px;"></div>
                            <div class="form-notch-middle" style="width: 40px;"></div>
                            <div class="form-notch-trailing"></div>
                        </div>
                    </div>
                    <br>
                    <div class="form-outline">
                        <select class="form-control active" id="lecturer_position" name="lecturer_position" type="text" required>
                            {% for val,type in option_position %}
                            <option value="{{val}}">{{type}}</option>
                            {% endfor %}
                        </select>
                        <label class="form-label" for="lecturer_position" style="margin-left: 0px;">Position</label>
                        <div class="form-notch">
                            <div class="form-notch-leading" style="width: 9px;"></div>
                            <div class="form-notch-middle" style="width: 50px;"></div>
                            <div class="form-notch-trailing"></div>
                        </div>
                    </div>
                    <br>
                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" role="switch" id="lecturer_active" name="lecturer_active"/>
                        <label class="form-check-label" for="lecturer_active">Active Lecturer</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
                    <button id="manage-lecturer" type="submit" class="btn btn-primary" name="manage-lecturer">Save
                        changes</button>
                </div>
            </div>
        </div>
    </div>
</form>

<!-- Modal -->
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<div class="modal fade" id="hod_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit Head of Department</h5>
          <button type="button" class="btn-close" data-mdb-ripple-init data-mdb-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="form-floating">
                
                <select class="form-select" id="new_hod" name="id">
                    {% for lecturer in lecturers %}
                    <option value="{{lecturer.id}}" {% if hod_name == lecturer.full_name %} selected {% endif %}>{{lecturer.full_name}}</option>
                    {% endfor %}
                </select>
                <label for="new_hod">Head of Department (new)</label>
            </div>
            
            <br>
          
            <label class="form-label" for="customFile">Signature:</label>
            <input type="file" class="form-control" id="signature" name="signature" accept=".jpg,.jpeg,.png" required/>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-mdb-ripple-init data-mdb-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" name="change-hod" data-mdb-ripple-init>Save changes</button>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}

templates/other_org_template.html
<div class="form-outline">
    <input type="text" id="org_name" name="org_name" class="form-control">
    <label class="form-label" for="org_name" style="margin-left: 0px;">Organisation Name</label>
    <div class="form-notch">
      <div class="form-notch-leading" style="width: 9px;"></div>
      <div class="form-notch-middle" style="width: 87.2px;"></div>
      <div class="form-notch-trailing"></div>
    </div>
  </div>
  <br>
  <div class="form-outline">
    <input type="year" id="org_year" name="org_year" class="form-control">
    <label class="form-label" for="org_year" style="margin-left: 0px;">Year</label>
    <div class="form-notch">
      <div class="form-notch-leading" style="width: 9px;"></div>
      <div class="form-notch-middle" style="width: 87.2px;"></div>
      <div class="form-notch-trailing"></div>
    </div>
  </div>

templates/password_reset.html
{% extends "sidebar.html" %}
{% block content %}
{% load static %}

    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                             maxlength="254" required id="id_email"
                                               placeholder="Enter your siswamail." onchange="val_email(this)" required>
                                    </div>
                                </div>
                            </div>
                            <br>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'register' %}">Create A New Account</a><br><br>
                                <a href="{% url 'login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}